<a href="https://colab.research.google.com/github/ChatMadhu/NN/blob/main/Wenner_Array_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import keras
from sklearn.model_selection import train_test_split

In [83]:
dataset = pd.read_csv('/content/Neural Network Sensor data - Copy  with other classes.csv')

In [84]:
dataset.shape

(454, 15)

In [85]:
dataset.head()

Date      Time   Temp  V(10mA)  V(10.5mA)  V(11mA)  V(11.5mA)  V(12mA)  \
0  5/8/2022  16:37:52  29.25     7.70       8.02     8.37       8.66     9.08   
1  5/8/2022  16:53:10  29.25     8.80       9.65    10.01      10.11    10.25   
2  5/8/2022  17:14:05  29.13     8.59       9.01     9.37       9.72    10.15   
3  5/8/2022  17:15:43  28.94     6.88       7.10     7.42       7.45     8.09   
4  5/8/2022  17:16:47  29.13     6.92       7.27     7.42       7.81     8.16   

   V(12.5mA)  V(13mA)  V(13.5mA)  V(14mA)  V(14.5mA)  sample number  \
0       9.44     9.83      10.04    10.40      10.57              1   
1      10.72    11.07      11.43    11.85      12.35              1   
2      10.54    10.89      11.25    11.60      12.03              1   
3       8.34     8.69       9.01     9.30       9.55              1   
4       8.45     8.76       9.01     9.26       9.69              1   

   Slinity_Class  
0              1  
1              1  
2              1  
3              1  
4              1

In [86]:
dataset.drop("sample number", axis=1, inplace=True)
dataset.drop("Date", axis=1, inplace=True)
dataset.drop("Time", axis=1, inplace=True)


In [87]:
dataset.head()

Temp  V(10mA)  V(10.5mA)  V(11mA)  V(11.5mA)  V(12mA)  V(12.5mA)  V(13mA)  \
0  29.25     7.70       8.02     8.37       8.66     9.08       9.44     9.83   
1  29.25     8.80       9.65    10.01      10.11    10.25      10.72    11.07   
2  29.13     8.59       9.01     9.37       9.72    10.15      10.54    10.89   
3  28.94     6.88       7.10     7.42       7.45     8.09       8.34     8.69   
4  29.13     6.92       7.27     7.42       7.81     8.16       8.45     8.76   

   V(13.5mA)  V(14mA)  V(14.5mA)  Slinity_Class  
0      10.04    10.40      10.57              1  
1      11.43    11.85      12.35              1  
2      11.25    11.60      12.03              1  
3       9.01     9.30       9.55              1  
4       9.01     9.26       9.69              1

In [88]:
dataset.tail()

Temp  V(10mA)  V(10.5mA)  V(11mA)  V(11.5mA)  V(12mA)  V(12.5mA)  \
449  28.52     4.63       5.16     5.83       6.79     6.94       7.92   
450  28.46     5.11       6.14     6.61       7.83     8.22       8.78   
451  28.91     4.50       6.35     6.47       6.90     7.02       7.98   
452  29.69     4.55       5.06     5.26       5.53     6.93       7.53   
453  28.49     4.42       4.65     6.10       6.84     6.88       7.27   

     V(13mA)  V(13.5mA)  V(14mA)  V(14.5mA)  Slinity_Class  
449     8.33       9.83    10.83      11.05              4  
450     9.00       9.69     9.99      10.16              4  
451     8.08       8.62     9.12      10.70              4  
452     8.78       8.86     9.29      10.81              4  
453     8.41       9.34    10.17      10.98              4

In [89]:
X = dataset.drop(columns='Slinity_Class',  axis=1)
Y = dataset['Slinity_Class']
print(X)
print(Y)

      Temp  V(10mA)  V(10.5mA)  V(11mA)  V(11.5mA)  V(12mA)  V(12.5mA)  \
0    29.25     7.70       8.02     8.37       8.66     9.08       9.44   
1    29.25     8.80       9.65    10.01      10.11    10.25      10.72   
2    29.13     8.59       9.01     9.37       9.72    10.15      10.54   
3    28.94     6.88       7.10     7.42       7.45     8.09       8.34   
4    29.13     6.92       7.27     7.42       7.81     8.16       8.45   
..     ...      ...        ...      ...        ...      ...        ...   
449  28.52     4.63       5.16     5.83       6.79     6.94       7.92   
450  28.46     5.11       6.14     6.61       7.83     8.22       8.78   
451  28.91     4.50       6.35     6.47       6.90     7.02       7.98   
452  29.69     4.55       5.06     5.26       5.53     6.93       7.53   
453  28.49     4.42       4.65     6.10       6.84     6.88       7.27   

     V(13mA)  V(13.5mA)  V(14mA)  V(14.5mA)  
0       9.83      10.04    10.40      10.57  
1      11.07      1

In [90]:
df=pd.DataFrame(dataset, columns = ['Temp', 'V(10mA)',	'V(10.5mA)',	'V(11mA)',	'V(11.5mA)',	'V(12mA)',	'V(12.5mA)',	'V(13mA)',	'V(13.5mA)',	'V(14mA)',	'V(14.5mA)',	'Slinity_Class'])

In [91]:
arr = df.to_numpy()
df

Temp  V(10mA)  V(10.5mA)  V(11mA)  V(11.5mA)  V(12mA)  V(12.5mA)  \
0    29.25     7.70       8.02     8.37       8.66     9.08       9.44   
1    29.25     8.80       9.65    10.01      10.11    10.25      10.72   
2    29.13     8.59       9.01     9.37       9.72    10.15      10.54   
3    28.94     6.88       7.10     7.42       7.45     8.09       8.34   
4    29.13     6.92       7.27     7.42       7.81     8.16       8.45   
..     ...      ...        ...      ...        ...      ...        ...   
449  28.52     4.63       5.16     5.83       6.79     6.94       7.92   
450  28.46     5.11       6.14     6.61       7.83     8.22       8.78   
451  28.91     4.50       6.35     6.47       6.90     7.02       7.98   
452  29.69     4.55       5.06     5.26       5.53     6.93       7.53   
453  28.49     4.42       4.65     6.10       6.84     6.88       7.27   

     V(13mA)  V(13.5mA)  V(14mA)  V(14.5mA)  Slinity_Class  
0       9.83      10.04    10.40      10.57              1  
1      11.07      11.43    11.85      12.35              1  
2      10.89      11.25    11.60      12.03              1  
3       8.69       9.01     9.30       9.55              1  
4       8.76       9.01     9.26       9.69              1  
..       ...        ...      ...        ...            ...  
449     8.33       9.83    10.83      11.05              4  
450     9.00       9.69     9.99      10.16              4  
451     8.08       8.62     9.12      10.70              4  
452     8.78       8.86     9.29      10.81              4  
453     8.41       9.34    10.17      10.98              4  

[454 rows x 12 columns]

In [92]:
X= np.asarray(X).astype('float32')
Y= np.asarray(Y).astype('float32')

In [114]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, stratify = Y, random_state = 4)

In [115]:
print(X.shape, X_test.shape, X_train.shape)

(454, 11) (46, 11) (408, 11)


In [116]:
print(X_train[1])

[28.89  4.95  5.87  6.    7.37  7.7   8.4   9.52  9.58 11.58 12.24]


In [117]:
print(Y_train[1])

3.0


In [118]:
print(X_train.shape)

(408, 11)


In [119]:
#ddevide by maximum number

X_train = X_train/30
X_test = X_test/30

In [120]:
X_train[1]

array([0.963     , 0.16499999, 0.19566666, 0.2       , 0.24566667,
       0.25666666, 0.28      , 0.31733334, 0.31933334, 0.386     ,
       0.408     ], dtype=float32)

In [129]:
X_test[0]

array([1.0103333 , 0.28266665, 0.29466668, 0.31166667, 0.31866667,
       0.31933334, 0.395     , 0.407     , 0.42833334, 0.44266665,
       0.46266666], dtype=float32)

In [130]:
Y_test[0]

2.0

In [131]:

model = keras.Sequential([
    keras.layers.Dense(10, input_shape = (11,), activation = 'relu'),
    keras.layers.Dense(10, input_shape = (10,), activation = 'relu'),
    keras.layers.Dense(4, activation = 'sigmoid')
])
model.compile(
    optimizer='adam',
    loss='KLDivergence',
    metrics=['accuracy']
)

model.fit(X_train, Y_train, epochs=60)

Epoch 1/60
13/13 [==============================] - 0s 2ms/step - loss: 2.6368 - accuracy: 0.2475
Epoch 2/60
13/13 [==============================] - 0s 2ms/step - loss: 2.5159 - accuracy: 0.2475
Epoch 3/60
13/13 [==============================] - 0s 2ms/step - loss: 2.3858 - accuracy: 0.2475
Epoch 4/60
13/13 [==============================] - 0s 2ms/step - loss: 2.2460 - accuracy: 0.2475
Epoch 5/60
13/13 [==============================] - 0s 2ms/step - loss: 2.0935 - accuracy: 0.2475
Epoch 6/60
13/13 [==============================] - 0s 2ms/step - loss: 1.9232 - accuracy: 0.2475
Epoch 7/60
13/13 [==============================] - 0s 2ms/step - loss: 1.7424 - accuracy: 0.2475
Epoch 8/60
13/13 [==============================] - 0s 2ms/step - loss: 1.5429 - accuracy: 0.2475
Epoch 9/60
13/13 [==============================] - 0s 3ms/step - loss: 1.3469 - accuracy: 0.2475
Epoch 10/60
13/13 [==============================] - 0s 2ms/step - loss: 1.1603 - accuracy: 0.2475
Epoch 11/60
13/13 [

In [124]:
Y_predicted = model.predict(X_test)
Y_predicted[0]

array([0.99535275, 0.99706316, 0.9920427 , 0.9974089 ], dtype=float32)

In [125]:
np.argmax(Y_predicted[0])

3

In [128]:
X_test[0]

array([1.0103333 , 0.28266665, 0.29466668, 0.31166667, 0.31866667,
       0.31933334, 0.395     , 0.407     , 0.42833334, 0.44266665,
       0.46266666], dtype=float32)